-- Create UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create ENUM types
CREATE TYPE user_kyc_status AS ENUM ('PENDING', 'IN_REVIEW', 'VERIFIED', 'REJECTED', 'EXPIRED');
CREATE TYPE transaction_status AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REFUNDED');
CREATE TYPE transaction_type AS ENUM ('TRANSFER', 'PAYMENT', 'REFUND', 'TOPUP');
CREATE TYPE payment_method_type AS ENUM ('BANK_ACCOUNT', 'DEBIT_CARD', 'CREDIT_CARD', 'MOBILE_MONEY', 'DIGITAL_WALLET', 'CRYPTOCURRENCY');
CREATE TYPE document_type AS ENUM ('PASSPORT', 'NATIONAL_ID', 'DRIVER_LICENSE', 'UTILITY_BILL', 'BANK_STATEMENT');
CREATE TYPE verification_status AS ENUM ('PENDING', 'VERIFIED', 'REJECTED', 'EXPIRED');
